image: "rust:latest"

before_script:
  - apt-get update -yqq
  - apt-get install -yqq --no-install-recommends build-essential gettext libpango1.0-dev oxygen-icon-theme cmake clang-tidy
  - apt-get install -yqq --no-install-recommends qtbase5-dev qtdeclarative5-dev libkf5configwidgets-dev kirigami2-dev libkf5plasma-dev libkf5i18n-dev libcairo2-dev libfontconfig1-dev libfreetype6-dev libgdk-pixbuf2.0-dev libglib2.0-dev libxml2-dev libpango1.0-dev
  - rustup component add clippy

stages:
  - commitlint
  - build
  - test
  - lint

commit_lint:
  stage: commitlint
  image: node:latest
    - if: '$CI_MERGE_REQUEST_IID'
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_TAG'
      when: never
    - when: always
  variables:
    UPSTREAM: https://invent.kde.org/sdk/ikona
  script:
    - if [ -n "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" ]; then export COMPARE_BRANCH=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME; else export COMPARE_BRANCH=master; fi
    - yarn global add @commitlint/cli
    - yarn add conventional-changelog-conventionalcommits
    - git remote add _upstream $UPSTREAM || git remote set-url _upstream $UPSTREAM
    - git fetch -q _upstream $COMPARE_BRANCH
    - commitlint --verbose --from=_upstream/$COMPARE_BRANCH
  cache:
    paths:
      - node_modules
  
cargo_build:
  stage: build
  script:
    - pushd src/rs
    - cargo build
    - popd
    
cmake_build:
  stage: build
  script:
    - mkdir _build
    - pushd _build
    - cmake ..
    - make -j8
    - popd

cargo_test:
  stage: test
  script:
    - pushd src/rs
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --all --verbose
    - popd

clang_tidy:
  allow_failure: true
  stage: lint
  script:
  - clang-tidy src/* -p _build -warnings-as-errors=\*

clippy:
  allow_failure: true
  stage: lint
  script:
  - pushd src/rs
  - cargo clippy -- -D warnings
  - popd
