image: "rust:latest"

before_script:
  - apt-get update -yqq
  - apt-get install -yqq --no-install-recommends build-essential gettext libpango1.0-dev oxygen-icon-theme
  - rustup component add clippy

stages:
  - test
  - lint

cargo_test:
  stage: test
  script:
    - cd src/rs
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --all --verbose

clippy:
  allow_failure: true
  stage: lint
  script:
  - cd src/rs
  - cargo clippy -- -D warnings